FROM python:3.13-slim
WORKDIR /app
RUN pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
COPY ./requirements.txt .
RUN pip install uvicorn
RUN pip install --no-cache-dir -r requirements.txt 
COPY . .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]