export var responseCode = {
    SUCCESS: 200,
    ERROR: 500,
    AUTH_ERROR: 10001,
    AUTH_EXPIRED: 10002,

    ERROR_NO_PERMISSION_TO_UPDATE_AND_VIEW_WORKSPACE: 5010,
    ERROR_WORKSPACE_INVITE_LINK_NOT_EXIST: 5011,
    ERROR_WORKSPACE_INVITE_LINK_EXPIRED: 5012,
    ERROR_WORKSPACE_MEMBER_EXIST: 5014,
    ERROR_WORKSPACE_INVITE_LINK_NOT_ALLOW_JOIN: 5015,
    ERROR_WORKSPACE_INVITE_LINK_NOT_MATCH: 5016,

}