# === Embedding / NLU Errors ===
ERROR_GET_INTENT = "ERR.GET_INTENT"
ERROR_GET_ACTION = "ERR.GET_ACTION"
ERROR_GENERATE_EMBEDDING = "ERR.GENERATE_EMBEDDING"
ERROR_MODEL_NOT_FOUND = "ERR.MODEL_NOT_FOUND"

# === Config / System Errors ===
ERROR_LOAD_CONFIG = "ERR.LOAD_CONFIG"
ERROR_INIT_SERVICE = "ERR.INIT_SERVICE"

# === Common Errors ===
ERROR_INVALID_REQUEST = "ERR.INVALID_REQUEST"
ERROR_INTERNAL = "ERR.INTERNAL"
