# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'
        
    - name: Set environment variables
      run: |
        echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV
        echo "BUILD_TIME=$(date +%FT%T%z)" >> $GITHUB_ENV
        
    - name: Download dependency
      run: go mod download
      
    - name: Build
      run: go build -ldflags "-X main.Version=${VERSION} -X main.BuildTime=${BUILD_TIME}" ./cmd/server

    - name: Test
      run: go test ./...
